openapi: 3.0.2

info:
  title: Swiftype Site Search API
  description: A first-party PHP client for the Elastic Site Search API.
  version: "1.0"

externalDocs:
  url: https://swiftype.com/documentation/site-search

components:
  # Reusable schemas definitions -----------------------------------------------
  schemas:
    simpleObject:
      type: object

  # Reusable parameters definitions --------------------------------------------
  parameters:
    engineNameParam:
      name: engine_name
      in: path
      description: Name of the engine.
      required: true
      schema:
        type: string

    documentTypeId:
      name: document_type_id
      in: path
      description: Document type id.
      required: true
      schema:
        type: string

  # Reusable request definitions -----------------------------------------------
  #requestBodies:


  # Reusable responses definitions ---------------------------------------------
  responses:
    jsonResponse:
      description: A simple JSON response.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/simpleObject"

paths:
  /engines.json:
    get:
      operationId: listEngines
      summary: Retrieves all engines with optional pagination support.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#list
      tags:
      - Engine API
      parameters:
      - name: page
        in: query
        description: The page to fetch. Defaults to 1.
        schema:
          type: string
        x-codegen-param-name: currentPage
      - name: per_page
        in: query
        description: The number of results per page.
        schema:
          type: string
        x-codegen-param-name: pageSize
      responses:
        default:
          $ref: "#/components/responses/jsonResponse"
    post:
      operationId: createEngine
      summary: Create a new API based engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#create
      tags:
      - Engine API
      parameters:
      - name: engine.name
        in: query
        required: true
        description: Engine name.
        schema:
          type: string
      - name: engine.language
        in: query
        description: Engine languager (null for universal).
        schema:
          type: string
      responses:
        default:
          $ref: "#/components/responses/jsonResponse"

  /engines/{engine_name}.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    get:
      operationId: getEngine
      summary: Retrieves an engine by name.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#one-engine
      tags:
      - Engine API
      responses:
        default:
          $ref: "#/components/responses/jsonResponse"
    delete:
      operationId: deleteEngine
      summary: Delete an engine by name.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#destroy
      tags:
      - Engine API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    post:
      operationId: createDocumentType
      summary: Create a new document type in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#add-documenttype
      tags:
      - Document API
      parameters:
      - name: document_type.name
        in: query
        required: true
        description: Document type name.
        schema:
          type: string
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
    get:
      operationId: listDocumentTypes
      summary: List all document types for an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#documenttypes-all
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    get:
      operationId: getDocumentType
      summary: Get a document type by id.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#documenttypes-single
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
    delete:
      operationId: deleteDocumentType
      summary: Delete a document type by id.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#documenttypes-delete
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
