openapi: 3.0.2

info:
  title: Swiftype Site Search API
  description: A first-party PHP client for the Elastic Site Search API.
  version: "1.0"

externalDocs:
  url: https://swiftype.com/documentation/site-search

components:
  # Reusable schemas definitions -----------------------------------------------
  schemas:
    simpleObject:
      type: object

    documentExternalId:
      type: string

    documentExternalIdList:
      type: array
      items:
        $ref: "#/components/schemas/documentExternalId"

    documentFieldSimpleValue:
      anyOf:
      - type: string
      - type: number

    documentFieldValue:
      anyOf:
      - $ref: "#/components/schemas/documentFieldSimpleValue"
      - type: array
        items:
          $ref: "#/components/schemas/documentFieldSimpleValue"

    documentField:
      type: object
      additionalProperties: false
      required:
      - name
      - value
      - type
      properties:
        name:
          type: string
        value:
          $ref: "#/components/schemas/documentFieldValue"
        type:
          type: string

    documentFieldList:
      type: array
      items:
        $ref: "#/components/schemas/documentField"

    documentFieldsUpdate:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/documentFieldValue"

    documentIndexBulk:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          external_id:
            $ref: "#/components/schemas/documentExternalId"
          fields:
            $ref: "#/components/schemas/documentFieldList"

  # Reusable parameters definitions --------------------------------------------
  parameters:
    engineNameParam:
      name: engine_name
      in: path
      description: Name of the engine.
      required: true
      schema:
        type: string

    documentTypeId:
      name: document_type_id
      in: path
      description: Document type id.
      required: true
      schema:
        type: string

    documentExternalId:
      name: external_id
      in: path
      description: Document external id.
      required: true
      schema:
        $ref: "#/components/schemas/documentExternalId"

  # Reusable request definitions -----------------------------------------------
  #requestBodies:


  # Reusable responses definitions ---------------------------------------------
  responses:
    jsonResponse:
      description: A simple JSON response.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/simpleObject"

paths:
  /engines.json:
    get:
      operationId: listEngines
      summary: Retrieves all engines with optional pagination support.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#list
      tags:
      - Engine API
      parameters:
      - name: page
        in: query
        description: The page to fetch. Defaults to 1.
        schema:
          type: string
        x-codegen-param-name: currentPage
      - name: per_page
        in: query
        description: The number of results per page.
        schema:
          type: string
        x-codegen-param-name: pageSize
      responses:
        default:
          $ref: "#/components/responses/jsonResponse"
    post:
      operationId: createEngine
      summary: Create a new API based engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#create
      tags:
      - Engine API
      parameters:
      - name: engine.name
        in: query
        required: true
        description: Engine name.
        schema:
          type: string
      - name: engine.language
        in: query
        description: Engine languager (null for universal).
        schema:
          type: string
      responses:
        default:
          $ref: "#/components/responses/jsonResponse"

  /engines/{engine_name}.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    get:
      operationId: getEngine
      summary: Retrieves an engine by name.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#one-engine
      tags:
      - Engine API
      responses:
        default:
          $ref: "#/components/responses/jsonResponse"
    delete:
      operationId: deleteEngine
      summary: Delete an engine by name.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/engines#destroy
      tags:
      - Engine API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    post:
      operationId: createDocumentType
      summary: Create a new document type in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#add-documenttype
      tags:
      - Document API
      parameters:
      - name: document_type.name
        in: query
        required: true
        description: Document type name.
        schema:
          type: string
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
    get:
      operationId: listDocumentTypes
      summary: List all document types for an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#documenttypes-all
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    get:
      operationId: getDocumentType
      summary: Get a document type by id.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#documenttypes-single
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
    delete:
      operationId: deleteDocumentType
      summary: Delete a document type by id.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#documenttypes-delete
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}/documents.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    post:
      operationId: createDocument
      summary: Create a new document in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#add-document
      tags:
      - Document API
      parameters:
      - name: document.external_id
        in: query
        required: true
        description: Document external id.
        schema:
          $ref: "#/components/schemas/documentExternalId"
      - name: document.fields
        in: query
        required: true
        description: Document fields.
        schema:
          $ref: "#/components/schemas/documentFieldList"
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
    get:
      operationId: listDocuments
      summary: List all documents in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#document-all
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}/documents/create_or_update.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    post:
      operationId: createOrUpdateDocument
      summary: Create or update a document in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#add-document
      tags:
      - Document API
      parameters:
      - name: document.external_id
        in: query
        required: true
        description: Document external id.
        schema:
          $ref: "#/components/schemas/documentExternalId"
      - name: document.fields
        in: query
        required: true
        description: Document fields.
        schema:
          $ref: "#/components/schemas/documentFieldList"
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}/documents/{external_id}.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    - $ref: "#/components/parameters/documentExternalId"
    get:
      operationId: getDocument
      summary: Retrieve a document from the engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#document-single
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
    delete:
      operationId: deleteDocument
      summary: Delete a document from the engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#delete-external-id
      tags:
      - Document API
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}/documents/{external_id}/update_fields.json:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    - $ref: "#/components/parameters/documentExternalId"
    put:
      operationId: updateDocumentFields
      summary: Update fields of a document.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#updating_fields
      tags:
      - Document API
      parameters:
      - name: fields
        in: query
        required: true
        description: Updated fields.
        schema:
          $ref: "#/components/schemas/documentFieldsUpdate"
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}/documents/bulk_create_or_update_verbose:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    post:
      operationId: bulkCreateOrUpdateDocuments
      summary: Bulk creation or update of documents in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#bulk_create_or_update_verbose
      tags:
      - Bulk API
      parameters:
      - name: documents
        in: query
        required: true
        description: List of documents to index.
        schema:
          $ref: "#/components/schemas/documentIndexBulk"
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}/documents/bulk_create:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    post:
      operationId: bulkCreateDocuments
      summary: Bulk creation of documents in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#bulk_create
      tags:
      - Bulk API
      parameters:
      - name: documents
        in: query
        required: true
        description: List of documents to create.
        schema:
          $ref: "#/components/schemas/documentIndexBulk"
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"

  /engines/{engine_name}/document_types/{document_type_id}/documents/bulk_update:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    put:
      operationId: bulkUpdateDocuments
      summary: Bulk update of documents in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#bulk_update
      tags:
      - Bulk API
      parameters:
      - name: documents
        in: query
        required: true
        description: List of documents to update.
        schema:
          $ref: "#/components/schemas/documentIndexBulk"
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"


  /engines/{engine_name}/document_types/{document_type_id}/documents/bulk_destroy:
    parameters:
    - $ref: "#/components/parameters/engineNameParam"
    - $ref: "#/components/parameters/documentTypeId"
    post:
      operationId: bulkDeleteDocuments
      summary: Bulk delete of documents in an engine.
      externalDocs:
        url: https://swiftype.com/documentation/site-search/indexing#bulk_destroy
      tags:
      - Bulk API
      parameters:
      - name: documents
        in: query
        required: true
        description: List of deleted documents external ids.
        schema:
          $ref: "#/components/schemas/documentExternalIdList"
      responses:
        default:
          $ref: "#/components/responseBodies/jsonResponse"
