version: 2.1

install: &install
  steps:
  - install_deps

unit_tests: &unit_tests
  steps:
  - run_unit_tests

integration_tests: &integration_tests
  environment:
    ST_ENGINE_NAME: php-integration-test-$CIRCLE_BUILD_NUM
  steps:
  - run_integration_tests

php73: &php73
  docker:
  - image: circleci/php:7.3-browsers

php72: &php72
  docker:
  - image: circleci/php:7.2-browsers

php71: &php71
  docker:
  - image: circleci/php:7.1-browsers

php70: &php70
  docker:
  - image: circleci/php:7.0-browsers

php56: &php56
  docker:
  - image: circleci/php:5.6-browsers

commands:
  install_deps:
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
    - run:
        name: Install composer dependencies
        command: composer install -n --prefer-dist
    - save_cache:
        paths:
        - ~/.composer/cache/
        key: v1-dependencies-{{ checksum "composer.json" }}
    - persist_to_workspace:
        root: .
        paths:
        - .
  run_unit_tests:
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Unit testing
        command: vendor/bin/phpunit -c phpunit.xml.dist --testsuite unit
  run_integration_tests:
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Integration testing
        command: ST_ENGINE_NAME="php-integration-test-$CIRCLE_BUILD_NUM" vendor/bin/phpunit -c phpunit.xml.dist --testsuite integration

jobs:

  php-73-install:
    <<: *install
    <<: *php73

  php-73-unit-tests:
    <<: *unit_tests
    <<: *php73

  php-73-integration-tests:
    <<: *integration_tests
    <<: *php73

  php-72-install:
    <<: *install
    <<: *php72

  php-72-unit-tests:
    <<: *unit_tests
    <<: *php72

  php-72-integration-tests:
    <<: *integration_tests
    <<: *php72

  php-71-install:
    <<: *install
    <<: *php71

  php-71-unit-tests:
    <<: *unit_tests
    <<: *php71

  php-71-integration-tests:
    <<: *integration_tests
    <<: *php71

  php-70-install:
    <<: *install
    <<: *php70

  php-70-unit-tests:
    <<: *unit_tests
    <<: *php70

  php-70-integration-tests:
    <<: *integration_tests
    <<: *php70

  php-56-install:
    <<: *install
    <<: *php56

  php-56-unit-tests:
    <<: *unit_tests
    <<: *php56

  php-56-integration-tests:
    <<: *integration_tests
    <<: *php56

workflows:
  version: 2
  build_and_test_73:
    jobs:
    - php-73-install
    - php-73-unit-tests:
        requires:
        - php-73-install
    - php-73-integration-tests:
        requires:
        - php-73-install
  build_and_test_72:
    jobs:
    - php-72-install
    - php-72-unit-tests:
        requires:
        - php-72-install
    - php-72-integration-tests:
        requires:
        - php-72-install
  build_and_test_71:
    jobs:
    - php-71-install
    - php-71-unit-tests:
        requires:
        - php-71-install
    - php-71-integration-tests:
        requires:
        - php-71-install
  build_and_test_70:
    jobs:
    - php-70-install
    - php-70-unit-tests:
        requires:
        - php-70-install
    - php-70-integration-tests:
        requires:
        - php-70-install
  build_and_test_56:
    jobs:
    - php-56-install
    - php-56-unit-tests:
        requires:
        - php-56-install
    - php-56-integration-tests:
        requires:
        - php-56-install
